### ISSUE TITLE
Quick fix for "readlink -f illegal option" on Mac

### ISSUE THREAD

**Issue by alicer3** [corda/corda-kubernetes-deployment#4] opened 2020-03-09 07:21 UTC
For anyone who encounters this issue on Mac
`brew install coreutils`
`export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"`
`alias readlink=greadlink`

**Comment by henrikr3** [comment] 2020-04-21 07:42
This should be fixed, but since I do not have a Mac, I will leave this issue open until confirmed by a Mac user.

**Comment by henrikr3** [comment] 2020-06-01 10:47
Got a hold of a macOS to test this issue. It has been resolved.

**Closed as completed by henrikr3** 2020-06-01 10:47 UTC
Labels: help wanted
